load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "dry",
    srcs = [
        "main.cpp",
        "Object.cpp",
        "Object.hpp",
        "LaneId.hpp", 
        "RelevantObjectsAcc.hpp",
        "RelevantObjectsAeb.hpp",
    ],
)