load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "adas",
    srcs = [
        "main.cpp",
        "Object.hpp",
        "ObjectList.hpp",
        "LaneId.hpp", 
        "RelevantObjectsAcc.cpp",
        "RelevantObjectsAcc.hpp",
        "RelevantObjectsAeb.cpp",
        "RelevantObjectsAeb.hpp",
    ],
)