load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "parking_lot",
    srcs = [
        "ParkingLotMain.cpp",
        "ParkingSpot.cpp",
    ],
    hdrs = [ "ParkingLot.hpp", "ParkingSpot.hpp", "Vehicle.hpp" ],
)
